"""extend health_records with flexible fields

Revision ID: 0d69509795d2
Revises: 
Create Date: 2026-08-05 09:23:58.120123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d69509795d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('result_value', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('result_unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('hospital_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('follow_up_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attachment_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachment_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_column('attachment_name')
        batch_op.drop_column('attachment_path')
        batch_op.drop_column('tags')
        batch_op.drop_column('follow_up_date')
        batch_op.drop_column('hospital_name')
        batch_op.drop_column('doctor_name')
        batch_op.drop_column('status')
        batch_op.drop_column('severity')
        batch_op.drop_column('result_unit')
        batch_op.drop_column('result_value')
        batch_op.drop_column('description')
        batch_op.drop_column('category')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
